import 'tailwindcss/tailwind.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Clothing</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://tailwindui.com/img/logos/workflow-mark.svg?color=indigo&shade=600"
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
